apps/matches/urls.py
from django.urls import path
from . import views

app_name = 'matches'

urlpatterns = [
    path('', views.list_matches, name='list_matches'),
    path('adicionar/', views.add_match, name='add_match'),
    path('editar/<int:id_match>/', views.edit_match, name='edit_match'),
    path('excluir/<int:id_match>/', views.delete_match, name='delete_match'),
]

projetogamesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jogadores_em_partidas/', include('playermatches.urls', namespace='playermatches')),
    path('partidas/', include('matches.urls', namespace='matches')),
    path('jogos/', include('games.urls', namespace='games')),
    path('itens/', include('items.urls', namespace='items')),
    path('jogadores/', include('players.urls', namespace='players')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/matches/models.py
from django.db import models
from games.models import Game

# Create your models here.

class Match(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    day = models.CharField('Dia', max_length=50)
    hour = models.CharField('Hora', max_length=50)
    
    class Meta:
        verbose_name = 'Partida'
        verbose_name_plural = 'Partidas'
        ordering =['id']

    def __str__(self):
        return self.game

apps/matches/forms.py
from django import forms
from .models import Match

class MatchForm(forms.ModelForm):

    class Meta:
        model = Match
        exclude = ('created_on' , 'updated_on',)

apps/matches/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import MatchForm
from .models import Match

# Create your views here.

def add_match(request):
    template_name = 'matches/add_match.html'
    context = {}
    if request.method == 'POST':
        form = MatchForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('matches:list_matches')
    form = MatchForm()
    context['form'] = form
    return render(request, template_name, context)

def list_matches(request):
    template_name = 'matches/list_matches.html'
    matches = Match.objects.filter()
    context = {
        'matches': matches
    }
    return render(request, template_name, context)

def edit_match(request, id_match):
    template_name = 'matches/add_match.html'
    context ={}
    match = get_object_or_404(Match, id=id_match)
    if request.method == 'POST':
        form = MatchForm(request.POST, request.FILES,  instance=match)
        if form.is_valid():
            form.save()
            return redirect('matches:list_matches')
    form = MatchForm(instance=match)
    context['form'] = form
    return render(request, template_name, context)

def delete_match(request, id_match):
    match = Match.objects.get(id=id_match)
    match.delete()
    return redirect('matches:list_matches')

templates/matches/add_match.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Partida - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Partida</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.game.id_for_label }}">Jogo</label>
                    {{ form.game|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.day.id_for_label }}">Dia</label>
                    {{ form.day|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.hour.id_for_label }}">Hora</label>
                    {{ form.hour|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/matches/list_matches.html
{% extends 'base.html' %}

{% block title %}

    Lista de Partidas - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Partidas</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'matches:add_match' %}">Cadastro de nova partida</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Jogo</th>
                    <th scope="col">Dia</th>
                    <th scope="col">Hora</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for match in matches %}
                        <tr>
                            <th scope="row">{{ match.id }}</th>
                            <td>{{ match.game }}</td>
                            <td>{{ match.day }}</td>
                            <td>{{ match.hour }}</td>
                            <td>
                                {% if match.is_active == True %}
                                    Ativo
                                {% endif %}
                                {% if match.is_active == False %}
                                    Inativo
                                {% endif %}
                            </td>
                            <td>{{ match.game }}</td>
                            <td>
                                <a href="{{ match.doc.url }}" >{{ match.doc.url }}</a>
                            </td>
                            <td>
                                <a href="{% url 'matches:edit_match' match.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>    
                                <a href="{% url 'matches:delete_match' match.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}