apps/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.list_games, name='list_games'),
    path('adicionar/', views.add_game, name='add_game'),
    path('editar/<int:id_game>/', views.edit_game, name='edit_game'),
    path('excluir/<int:id_game>/', views.delete_game, name='delete_game'),
]

apps/items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('', views.list_items, name='list_items'),
    path('adicionar/', views.add_item, name='add_item'),
    path('editar/<int:id_item>/', views.edit_item, name='edit_item'),
    path('excluir/<int:id_item>/', views.delete_item, name='delete_item'),
]

apps/matches/urls.py
from django.urls import path
from . import views

app_name = 'matches'

urlpatterns = [
    path('', views.list_matches, name='list_matches'),
    path('adicionar/', views.add_match, name='add_match'),
    path('editar/<int:id_match>/', views.edit_match, name='edit_match'),
    path('excluir/<int:id_match>/', views.delete_match, name='delete_match'),
]

apps/players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('', views.list_players, name='list_players'),
    path('adicionar/', views.add_player, name='add_player'),
    path('editar/<int:id_player>/', views.edit_player, name='edit_player'),
    path('excluir/<int:id_player>/', views.delete_player, name='delete_player'),
    path('buscar/', views.search_players, name='search_players'),
]

projetogamesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jogadores_em_partidas/', include('playermatches.urls', namespace='playermatches')),
    path('partidas/', include('matches.urls', namespace='matches')),
    path('jogos/', include('games.urls', namespace='games')),
    path('itens/', include('items.urls', namespace='items')),
    path('jogadores/', include('players.urls', namespace='players')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Game Creator{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Game Creator</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'players:list_players' %}">Jogadores</a>
                        <a class="dropdown-item" href="{% url 'playermatches:list_playermatches' %}">Jogadores em partidas</a>
                        <a class="dropdown-item" href="{% url 'matches:list_matches' %}">Partidas</a>
                        <a class="dropdown-item" href="{% url 'games:list_games' %}">Jogos</a>
                        <a class="dropdown-item" href="{% url 'items:list_items' %}">Equipamentos</a>
                    </div>
                </li>
            </ul>
            <form action="{% url 'players:search_players' %}" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
                <input class="form-control" name="query" type="text" placeholder="Sobrenome do jogador" aria-label="Buscar" style="margin-right: 10px">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>            
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Nome de usuario</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown05">
                            <a class="dropdown-item" href="#">Trocar senha</a>
                            <a class="dropdown-item" href="#">Conta</a>                            
                            <a class="dropdown-item" href="#">Sair</a>
                        </div>
                    </li>
                </ul>
        </div>
    </nav>
    {% block body %}
    
    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>