apps/items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path('', views.list_items, name='list_items'),
    path('adicionar/', views.add_item, name='add_item'),
    path('editar/<int:id_item>/', views.edit_item, name='edit_item'),
    path('excluir/<int:id_item>/', views.delete_item, name='delete_item'),
]

projetogamesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jogadores_em_partidas/', include('playermatches.urls', namespace='playermatches')),
    path('partidas/', include('matches.urls', namespace='matches')),
    path('jogos/', include('games.urls', namespace='games')),
    path('itens/', include('items.urls', namespace='items')),
    path('jogadores/', include('players.urls', namespace='players')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/items/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    name = models.CharField('Nome', max_length=50)
    element = models.CharField('Elemento', max_length=50)
    description = models.TextField('Descricao', max_length=100) 
    TYPE_CHOICES = (
        ('ARM', 'Arma'),
        ('ARD', 'Armadura'),
        ('CON', 'Consumivel'),
    )
    type = models.CharField('Tipo', max_length=3, choices=TYPE_CHOICES)    
    class Meta:
        verbose_name = 'Equipamento'
        verbose_name_plural = 'Equipamentos'
        ordering =['id']

    def __str__(self):
        return self.name
    

apps/items/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        exclude = ('created_on' , 'updated_on',)

apps/items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ItemForm
from .models import Item

# Create your views here.

def add_item(request):
    template_name = 'items/add_item.html'
    context = {}
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('items:list_items')
    form = ItemForm()
    context['form'] = form
    return render(request, template_name, context)

def list_items(request):
    template_name = 'items/list_items.html'
    items = Item.objects.filter()
    context = {
        'items': items
    }
    return render(request, template_name, context)

def edit_item(request, id_item):
    template_name = 'items/add_item.html'
    context ={}
    item = get_object_or_404(Item, id=id_item)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('items:list_items')
    form = ItemForm(instance=item)
    context['form'] = form
    return render(request, template_name, context)

def delete_item(request, id_item):
    item = Item.objects.get(id=id_item)
    item.delete()
    return redirect('items:list_items')

# REVISADO

templates/items/add_item.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Equipamento - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Equipamento</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.element.id_for_label }}">Elemento</label>
                    {{ form.element|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Descricao</label>
                    {{ form.description|add_class:"form-control" }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.type.id_for_label }}">Tipo</label>
                    {{ form.type|add_class:"form-control" }}
                 </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/items/list_items.html
{% extends 'base.html' %}

{% block title %}

    Lista de Equipamentos - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Equipamentos</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'items:add_item' %}">Cadastro de novo equipamento</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Elemento</th>
                    <th scope="col">Descricao</th>
                    <th scope="col">Tipo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                        <tr>
                            <th scope="row">{{ item.id }}</th>
                            <td>{{ item.name }}</td>
                            <td>{{ item.element }}</td>
                            <td>{{ item.description }}</td>
                            <td>{{ item.type }}</td>
                            <td>
                                <a href="{% url 'items:edit_item' item.id %}" class="btn btn-primary btn-sm">Editar</a>
                                <a href="{% url 'items:delete_item' item.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}