apps/playermatches/urls.py
from django.urls import path
from . import views

app_name = 'playermatches'

urlpatterns = [
    path('', views.list_playermatches, name='list_playermatches'),
    path('adicionar/<int:id_client>/', views.add_playermatch, name='add_playermatch'),
    path('excluir/<int:id_playermatch>/', views.delete_playermatch, name='delete_playermatch'),
    path('excluir-item/<int:id_playermatch_item>/', views.delete_playermatch_item, name='delete_playermatch_item'),
    path('adicionar-item/<int:id_playermatch>/', views.add_playermatch_item, name='add_playermatch_item'),
    path('editar-status/<int:id_playermatch>/', views.edit_playermatch_status, name='edit_playermatch_status'),
]

apps/players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('', views.list_players, name='list_players'),
    path('adicionar/', views.add_player, name='add_player'),
    path('editar/<int:id_player>/', views.edit_player, name='edit_player'),
    path('excluir/<int:id_player>/', views.delete_player, name='delete_player'),
    path('buscar/', views.search_players, name='search_players'),
]

projetogamesapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jogadores_em_partidas/', include('playermatches.urls', namespace='playermatches')),
    path('partidas/', include('matches.urls', namespace='matches')),
    path('jogos/', include('games.urls', namespace='games')),
    path('itens/', include('items.urls', namespace='items')),
    path('jogadores/', include('players.urls', namespace='players')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/playermatches/models.py
from django.db import models
from matches.models import Match
from players.models import Player

# Create your models here.

class PlayerMatch(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    STATUS_CHOICES = (
        ('Em andamento', 'Em andamento'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Em andamento')

    class Meta:
        verbose_name = 'Jogador em Partida'
        verbose_name_plural = 'Jogadores em Partidas'
        ordering =['id']

    def __str__(self):
        return "%s" % (self.player) 

class PlayerMatchItem(models.Model):
    playermatch = models.ForeignKey(PlayerMatch, on_delete=models.CASCADE)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    quantity = models.IntegerField('Quantidade',null=True, blank=True,default=0)

    class Meta:
        verbose_name = 'Partida do Jogador'
        verbose_name_plural = 'Partidas do Jogador'
        ordering =['id']

    def __str__(self):
        return "%s" % (self.playermatch) 

apps/playermatches/forms.py
from django import forms
from .models import PlayerMatch, Player, PlayerMatchItem, Match

class PlayerMatchForm(forms.ModelForm):
    
    class Meta:
        model = PlayerMatch
        exclude = ('player', 'created_on' , 'updated_on')

class PlayerMatchItemForm(forms.ModelForm):
        
    class Meta:
        model = PlayerMatchItem
        exclude = ('playermatch', 'created_on' , 'updated_on')

apps/playermatches/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PlayerMatchForm, PlayerMatchItemForm
from .models import PlayerMatch, PlayerMatchItem, Match, Player

# Create your views here.

def add_playermatch(request, id_player):
    template_name = 'playermatches/add_playermatch.html'
    context = {}
    if request.method == 'POST':
        form = PlayerMatchForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.player = Player.objects.get(id=id_player)
            f.save()
            form.save_m2m()
            return redirect('playermatches:list_playermatches')
    form = PlayerMatchForm()
    context['form'] = form
    return render(request, template_name, context)

def list_playermatches(request):
    template_name = 'playermatches/list_playermatches.html'
    playermatches = PlayerMatch.objects.filter()
    matches = Match.objects.filter()
    players = Player.objects.filter()
    context = {
        'playermatches': playermatches,
        'matches': matches,
        'players': players
    }
    return render(request, template_name, context)

def delete_playermatch(request, id_playermatch):
    playermatch = PlayerMatch.objects.get(id=id_playermatch)
    playermatch.delete()
    return redirect('playermatches:list_playermatches')

def add_playermatch_item(request, id_playermatch):
    template_name = 'playermatches/add_playermatch_item.html'
    context = {}
    if request.method == 'POST':
        form = PlayerMatchItemForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.playermatch = PlayerMatch.objects.get(id=id_playermatch)
            f.save()
            form.save_m2m()
            return redirect('playermatches:list_playermatches')
    form = PlayerMatchItemForm()
    context['form'] = form
    return render(request, template_name, context)

def delete_playermatch_item(request, id_playermatch_item):
    playermatchitem = PlayerMatchItem.objects.get(id=id_playermatch_item)
    playermatchitem.delete()
    return redirect('playermatches:list_playermatches')

def edit_playermatch_status(request, id_playermatch):
    template_name = 'playermatches/edit_playermatch_status.html'
    context ={}
    playermatch = get_object_or_404(PlayerMatch, id=id_playermatch)
    if request.method == 'POST':
        form = PlayerMatchForm(request.POST, instance=playermatch)
        if form.is_valid():
            form.save()
            return redirect('playermatches:list_playermatches')
    form = PlayerMatchForm(instance=playermatch)
    context['form'] = form
    return render(request, template_name, context)

templates/playermatches/add_playermatch.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Jogador em Partida - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Deseja adicionar um jogador? </b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-sm">Sim</button>   <a href="{% url 'players:list_players' %}" class="btn btn-primary btn-sm">Nao</a>     
                </form>
                
            </div>
        </div>
    </div>

{% endblock body %}

templates/playermatches/add_playermatch_item.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Jogador na Partida - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Adicionar Jogador na Partida</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
                    {{ form.quantity|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.player.id_for_label }}">Jogador</label>
                    {{ form.player|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.match.id_for_label }}">Partida</label>
                    {{ form.match|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/playermatches/edit_playermatch_status.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Jogador na Partida - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Alterar Status do Jogador</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.status.id_for_label }}">Status</label>
                    {{ form.status|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Alterar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/playermatches/list_playermatches.html
{% extends 'base.html' %}

{% block title %}

    Jogadores em Partidas - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Jogadores em Partidas</b></h5>
        <div class="row">
            <div class ="col-md-12">
            <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Status</th>
                    <th scope="col">Jogador</th>
                    <th scope="col">Partidas do Jogador</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for playermatch in playermatch %}
                        <tr>
                            <th scope="row">
                                {% if playermatch.status == 'Finalizado' or playermatch.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >{{ playermatch.id }}</p>
                                {% else %}
                                    {{ playermatch.id }}
                                {% endif %}
                            </th>
                            <td>
                                {% if playermatch.status == 'Finalizado' or playermatch.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >{{ playermatch.status }}</p>
                                {% else %}
                                    {{ playermatch.status }}
                                {% endif %}
                            </td>
                            <td>
                                {% for player in players %}
                                    {% if playermatch.player_id == player.id %}
                                        {% if playermatch.status == 'Finalizado' or playermatch.status == 'Cancelado' %}
                                            <p style="color:darkgray;" >{{ player.first_name }} {{ player.last_name }}</p>
                                        {% else %}
                                            {{ player.first_name }} {{ player.last_name }}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}   
                            </td>
                            <td>
                                {% if playermatch.status == 'Finalizado' or playermatch.status == 'Cancelado' %}
                                    <a href="#" class="btn btn-primary btn-sm disabled">Adicionar itens</a>
                                {% else %}
                                    <a href="{% url 'playermatches:add_playermatch_item' playermatch.id %}" class="btn btn-primary btn-sm">Adicionar itens</a>
                                {% endif %}
                                <br /><br />
                                {% for playermatch_item in playermatches_items %}
                                    {% if playermatch_item.playermatch_id == playermatch.id %}
                                        Partida: {{ playermatch_item.match}}<br /> 
                                        Jogador: {{ playermatch_item.player}}<br />
                                        Quantidade: {{ playermatch_item.quantity}}<br />
                                        <a href="{% url 'playermatches:delete_playermatch_item' playermatch_item.id %}">Excluir Item</a><br /><br />
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'playermatches:edit_playermatch_status' playermatch.id %}" class="btn btn-danger btn-sm ">Alterar Status</a>
                            </td>
                            <td>
                                <a href="{% url 'playermatches:delete_playermatch' playermatch.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}

<!--POSSÍVEL ERRO COM ORDER.STATUS-->